PassionProject/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.SqlClient;
using System.Data.Entity;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PassionProject.Models;
using PassionProject.Models.ViewModels;
using System.Diagnostics;

namespace PassionProject.Controllers
{
    public class GameController : Controller
    {
        //Variable to hold the db
        private ReviewCMSContext db = new ReviewCMSContext();

        //Have to create methods for create, read, update, and delete.
        //Create: New and Create
        //Read: Show
        //Update: Edit
        //Delete: Delete
        //
        //Current methods: Add, Create, 

        public ActionResult Add()
        {
            return View(db.Games);
        }

        //For the create: We write a string query with some of the
        //parameters in the query with the prefix @, then we execute
        //the db.Database.ExecuteSqlCommand passing four SqlParameters.
        //Here we use an array but we don't really need to as long as
        //we pass four SqlParameters...
        [HttpPost]
        public ActionResult Create(string gametitle,
            string releasedate, string publisher)
        {
            //My columns are in the query below...
            string query = "insert into games (" +
                "GameTitle, ReleaseDate, Publisher)" +
                "values ( @game_title, @release_date, " +
                "@publisher)";

            Debug.WriteLine(query);

            //SqlParameter[x] is an array of x SqlParameters.
            //SqlParameter("str", p) is an individual SqlParameter.
            SqlParameter[] gameparams = new SqlParameter[3];
            
            gameparams[0] = new SqlParameter("@game_title", gametitle);
            gameparams[1] = new SqlParameter("@release_date", releasedate);
            gameparams[2] = new SqlParameter("@publisher", publisher);

            db.Database.ExecuteSqlCommand(query, gameparams);

            return RedirectToAction("Manage");
        }

        //For Show (view), all we need to do is return a View. View has one parameter
        //which is a query which we call with db.Games.SqlQuery passing the @parameter
        //and parameter.

        public ActionResult Show(int id)
        {
            string query = "select * from games where gameid = @id";
            return View(db.Games.SqlQuery(query, new SqlParameter("@id", id)).FirstOrDefault());
        }

        public ActionResult Manage()
        {
            //data needed: all games in DB
            return View(db.Games.ToList());
        }
            
        public ActionResult Index()
        {
            return RedirectToAction("Manage");
        }
        public ActionResult Delete(int id)
        {
            //Create a query where @id is the id passed to the method
            string query = "delete from games where gameid = @id";
            
            //Execute the SQL query
            db.Database.ExecuteSqlCommand(query, new SqlParameter("@id", id));

            //Here is where you would delete any references to this game in
            //the gamereviews table then execute the query.
            //query = "delete from gamereviews where gameid = @id";
            //db.Database.ExecuteSqlCommand(query, new SqlParameter("@id", id));

            //Why doesn't it just call the list method?
            return RedirectToAction("Manage");
        }
        //For Edit, we create a new GameReviewEdit object 
        /*
        public ActionResult Edit(int? id)
        {
            //We edit by creating a pageedit object.
            PageEdit pageedit = new PageEdit();

            pageedit.game = db.Games.Find(id);
            pageedit.gamereview = db.gamereviews.ToList();

            if (pageedit.game != null)
            {
                return View(pageedit);
            } else
            {
                return HttpNotFound();
            }
        }
        */
        /*
        public ActionResult Edit(int? gameid, string gametitle, string releasedate, string publisher)
        {
            if ((gameid == null) || (db.Pages.Find(gameid) == null))
            {
                return HttpNotFound();
            }
            string query = "update games set gametitle = @title, " +
                "releasedate = @releasedate, publisher = @publisher " +
                "where gameid = @gameid";

            //Create an array of game parameters like before
            SqlParameter[] gameparams = new SqlParameter[3];

            gameparams[0] = new SqlParameter();
            gameparams[0].ParameterName = "@gametitle";
            gameparams[0].Value = gametitle;

            gameparams[1] = new SqlParameter();
            gameparams[1].ParameterName = "@releasedate";
            gameparams[1].Value = releasedate;

            gameparams[2] = new SqlParameter();
            gameparams[2].ParameterName = "@publisher";
            gameparams[2].Value = publisher;

            return RedirectToAction("Show/" + gameid);
        }
        */
    }
}

PassionProject/Controllers/GameReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.SqlClient;
using System.Data.Entity;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PassionProject.Models;
using System.Diagnostics;

namespace PassionProject.Controllers
{
    public class GameReviewController : Controller
    {
        private ReviewCMSContext db = new ReviewCMSContext();


        public ActionResult Manage()
        {
            return View(db.Reviews.ToList());
        }
        public ActionResult Add()
        {
            return View(db.Reviews.ToList());
        }
        public ActionResult Create(string reviewtitle, string content, string rating, string ratingcomment)
        {
            string query = "Insert into GameReviews (reviewTitle, content, rating, ratingComment)" +
                "Values (@reviewTitle, @content, @rating, @ratingComment)";

            SqlParameter[] gamereviewparams = new SqlParameter[4];

            gamereviewparams[0] = new SqlParameter("@reviewTitle", reviewtitle);
            gamereviewparams[1] = new SqlParameter("@content", content);
            gamereviewparams[2] = new SqlParameter("@rating", rating);
            gamereviewparams[3] = new SqlParameter("@ratingComment", ratingcomment);
            //gamereviewparams[4] = new SqlParameter("@game_GameId", gameId);

            db.Database.ExecuteSqlCommand(query, gamereviewparams);

            return RedirectToAction("Manage");
        }
        public ActionResult Delete(int id)
        {
            string query = "Delete from gamereviews where Game_review_ID = @id";

            db.Database.ExecuteSqlCommand(query, new SqlParameter("@id", id));

            return RedirectToAction("Manage");
        }
        public ActionResult Show(int id)
        {
            string query = "Select * from gamereviews where Game_review_ID = @id";
            return View(db.Games.SqlQuery(query, new SqlParameter("@id", id)).FirstOrDefault());
        }
        public ActionResult Edit(int id)
        {
            return View(db.Reviews.ToList());
        }
        //Gam
        
        public ActionResult Edit_it(string reviewtitle, string content, string rating, string ratingcomment)
        {
            string query = "update gamereviews set reviewTitle=@reviewtitle, " +
                "content=@content, rating=@rating, ratingComment=@ratingcomment";

            //Borrowing the idea of the array of parameters from the code example...
            SqlParameter[] reviewParams = new SqlParameter[4];

            reviewParams[0] = new SqlParameter();
            reviewParams[0].ParameterName = "@reviewTitle";
            reviewParams[0].Value = reviewtitle;

            reviewParams[1] = new SqlParameter();
            reviewParams[1].ParameterName = "@content";
            reviewParams[1].Value = content;

            reviewParams[2] = new SqlParameter();
            reviewParams[2].ParameterName = "@rating";
            reviewParams[2].Value = rating;

            reviewParams[3] = new SqlParameter();
            reviewParams[3].ParameterName = "@ratingComment";
            reviewParams[3].Value = ratingcomment;

            db.Database.ExecuteSqlCommand(query, reviewParams);
            return RedirectToAction("Manage");
        }
    }
}

PassionProject/Views/GameReview/Add.cshtml
<h2>Add new review</h2>

@Html.ActionLink("Go back to list", "Manage", "GameReview")

<!--The action calls the GameReview controller and the Create method within.-->
<form method="POST" action="/GameReview/Create">
    <label>Game:</label>
    <input type="text" name="game">

    <br><label>Review title:</label>
    <input type="text" name="reviewTitle">

    <br><label>Content:</label>
    <input type="text" name="content">

    <br><label>Rating:</label>
    <input type="text" name="rating">

    <br><label>Rating comment:</label>
    <input type="text" name="ratingComment">

    <input type="submit" value="submit">
</form>

PassionProject/Views/GameReview/Delete.cshtml
<h1>Delete game</h1>

@Html.ActionLink("Go back to Manage", "Manage", "GameReview")

<!--Only input should be delete button-->
<form method="POST" action="/GameReview/Delete">
    <input type="submit" value="submit">
</form>

PassionProject/Views/GameReview/Edit.cshtml
<h1>Edit game review</h1>

@Html.ActionLink("Back to Manage", "Manage", "GameReview")

<!--Form inputs: Game, reviewTitle, content, rating, ratingComment -->
<form method="POST" action="/GameReview/Edit_it">
    <label>Review title:</label><input type="text" name="reviewTitle" />
    <br><label>Content:</label><input type="text" name="content" />
    <br><label>Rating:</label><input type="text" name="rating" />
    <br><label>Rating comment:</label><input type="text" name="ratingComment" />
    <br><input type="submit" value="submit" />
</form>

PassionProject/Views/GameReview/Manage.cshtml
<!--CONNECT THE VIEW TO THE MODEL-->
@model IEnumerable<PassionProject.Models.GameReview>


<h1>Manage Game Reviews</h1>

@Html.ActionLink("Go to games", "Manage", "Game")
<br>
@Html.ActionLink("Add new review", "Add", "GameReview")

@foreach (var gamereview in Model)
{
    <h2>@gamereview.reviewTitle</h2>
    <h5>@gamereview.game</h5>
    <p>@Html.ActionLink("Show this review", "Show", "GameReview", new { id = gamereview.Game_review_ID, title = gamereview.reviewTitle }, null)</p>
    <p>@Html.ActionLink("Delete this review", "Delete", "GameReview", new { id = gamereview.Game_review_ID, title = gamereview.reviewTitle }, null)</p>
    <p>@Html.ActionLink("Edit this review", "Edit", "GameReview", new { id = gamereview.Game_review_ID, title = gamereview.reviewTitle }, null)</p>
}

PassionProject/Views/GameReview/Show.cshtml
<h1>Show game review</h1>

@Html.ActionLink("Back to Manage", "Manage", "GameReview")
@Html.ActionLink("Delete this game", "Delete", "GameReview")
@Html.ActionLink("Edit this game", "Edit", "GameReview")